LOCKVALUE: 99999
VIDEO:
  STREAM: "results/v1.mp4"
  MULTI_THREAD: true
  ACQUISITION_W: 1920
  ACQUISITION_H: 1080
  TARGET_W: 3840
  TARGET_H: 2160
  SAVE_VIDEO: True
  SAVED_VIDEO_PATH: "annotations_output.mp4"
  CAP_FPS: 25

DETECTOR:
  CKPT_PATH: "weights/detector/yolov7-tiny.pt"
  BATCH_PROCESSING_FRAMES: 64
  INFERENCE_W: 1920
  INFERENCE_H: 1080
  CONF_TH: 0.6
  IOU_TH: 0.45
  PERSON_EXTEND_SCALE: 80
  DO_SAVE_ALERT: True
  DEVICE: "cpu"
  TRACKER:
    TYPE: "bytetrack"
    MATCH_THRESHOLD: 0.3
    OUT_THRESHOLD: 0.3
    TRACK_THRESHOLD: 0.3
    TRACK_BUFFER: 30
